### PR TITLE
Add Startpage to selectable search engines

### PR DESCRIPTION
**Pull request by felfert**
Subject says it all.
Since I was not able to save it as a custom search engine, I added my favorite search engine to the
list of selectable search engines :-)

Cheers
 -Fritz

### CODE REVIEW

**Comment by sorryusernameisalreadytaken** [comment]
Thank you. I was searching if somebody add this already and see your PR here.

Keep on mind that startpage want users to add search there searchengine with [OpenSearch ](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) protocol. Using this query-method a lot reults in a temporary ban (I think IP block).

**Comment by MailYouLater** [comment]
LGTM

> Keep on mind that startpage want users to add search there searchengine with [OpenSearch ](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) protocol.

Where did this statement come from?  I've been digging through Startpage's documentation and experimenting with using it for the past few hours and I haven't seen any mention of OpenSearch anywhere on their website.  Also, I don't see how OpenSearch is relevant to this discussion at all.  OpenSearch is a way for a website to advertise its search function to supporting browsers, so that they can effectively autodiscover the appropriate url to use, which simplifies the process the user needs to go through to add that site as a custom search engine to their browser.  TV Bro doesn't support OpenSearch (yet?), and this PR is to add Startpage as one of the default search engine options, not a custom one.

> Using this query-method a lot reults in a temporary ban (I think IP block).

Again, where is this coming from?  I see no indication of this on their site, rather I see them recommending users to manually add them as a custom search engine exactly as this PR does.  See [Search strings / adding Startpage to unsupported web browsers](https://support.startpage.com/hc/en-us/articles/4520913488148-Search-strings-adding-Startpage-to-unsupported-web-browsers) for confirmation.

Also, if you actually add Startpage to a browser using the OpenSearch based auto-discovery, it actually uses the same (as you called it) "query-method", the only real differences being that it adds a few more parameters (specifically `&cat=web&pl=opensearch&language=english` for me, I guess they might detect location or language settings to pick the `language`) and that it offers a URL template for search suggestions, which the browser can use if it supports them.

So again, if we want Startpage as a built-in search engine option, then this PR looks good to me.

**Comment by sorryusernameisalreadytaken** [comment]
Thanks @MailYouLater @felfert for your links. My information was a few years old :D
But I personally use startpage.com on every device I can get my hands on. So I regularly set up this custom default engine. In my experience, this often results in a temporary lock if you use search a certain amount of time. However, this only happens when I need to use this type:
https://support.startpage.com/hc/en-us/articles/4520913488148-Search-strings-adding-Startpage-to-unsupported-web-browsers
If I use the official addon or Opensearch, I never get a lock. And when I say "never", I mean over the last 5 years of using startpage.com on many different systems and networks.

Startpage.com uses a paid API from Google and gets money for it. So it makes sense that startpage.com doesn't explain exactly how the banning system works to prevent bot usage/abuse and so on.

So it's just my personal experience and the only thing I wanted to do was write this. Sorry if I printed it insufficiently.

**Review by truefedex — APPROVED** [review]

**Comment by truefedex** [comment]
Thank you @felfert for this contribution!

**Comment by MailYouLater** [comment]
> In my experience, this often results in a temporary lock if you use search a certain amount of time.

What kind of "temporary lock"?  Does it give you an error message/number? (What is it?) or does it ask for a captcha? or something else? (What?)

> However, this only happens when I need to use this type: [...] If I use the official addon or Opensearch, I never get a lock.

There's a couple of reasons I can think of that could explain this...

You stated earlier that you use Startpage on 'every device [you] can get [your] hands on', so assuming that you'll be setting the default search engine on your TV Bro installation(s), please report back if you find that this implementation ends up getting subjected to these blocks. Thanks.

**Pull request merged**
