### PR TITLE
Add Polish translation from #103

### PR DESCRIPTION
**Pull request by MailYouLater**
This is the Polish translation submitted by BadOmen aka Bartosz Hnat in issue #103.  Since he [says](https://github.com/truefedex/tv-bro/issues/103#issuecomment-1139912404) "I have no patience for git hub" I made this PR for him, to make it easier to merge.

"System" still hasn't been translated, I don't speak Polish, so all I can say is that a similar setting in Firefox is "Use system colors" in English and translated to Polish as "Kolory systemowe".

### CODE REVIEW

**Comment by BartoszHnat** [comment]
Thanks - now i know contex - we can translate "System" into "Użyj koloru systemu" (Use system colors) but i think it will be in select from dark, light apperance - so "system" will also be good.
So you can select both are good 
a)Użyj kolorów systemu
b)System
Choice is yours.

**Comment by MailYouLater** [comment]
Giving me the choice doesn't make much sense, since I don't speak Polish, so I don't know what would seem most natural/awkward to a Polish speaker.  Also, I did make sure to give that context when I posted in #103.

Anyway, if I were to choose, I would think that since the English and Ukrainian translations are each a single word ("System" & "Системна" respectively) a single Polish word would likely be best, however, I don't know polish, so for all I know that could leave it with insufficient context for a native Polish speaker.

So... in the end, I guess we'll leave it as "System" as truefedex said "missing translations will be complemented with google translate", and even though it looks to me like a missing translation... I guess it's right? or at least right enough for now, and if someone comes along with a better translation, we can fix it then...

@truefedex: I'm done with this PR.

**Comment by BartoszHnat** [comment]
So if i were to choose.. i would pick "kolory systemowe" but "System" is good too.

**Comment by MailYouLater** [comment]
.....
OK, I guess I'm not quite done with this PR yet...

Give me a few minutes to swap "Kolory systemowe" in instead of "System", take out the `translatable="false"` lines (I noticed that truefedex removed them from the Vietnamese translation, so it seems they're not supposed to be there), and ... I guess I may as well rewrite it into a single commit.  Then I'll really be done with it.

**Comment by MailYouLater** [comment]
Oh... Looks like I forgot to come back and say that I was done.

Anyway, @truefedex: Unless you see something wrong with this PR, I'm done with it.

**Pull request merged**
