### PR TITLE
Added ability to set search engine as homepage

### PR DESCRIPTION
**Pull request by E-D-W-I-N**
### Added ability to set search engine as homepage.

Some search engines (such as Yandex) has some additional info at the search page, for example news, weather etc. So it's very useful to open it by default.

Screenshot_1641489865

P.S. This change is lacking translation for Persian, Hebrew, Ukrainian, Vietnamese and Chinese. I've added translation for English and Russian.

### CODE REVIEW

**Comment by tvbrogreat** [comment]
Thanks for probably the best browser for android tv!

Could this setting be modified and added to enable any custom url as startup page: "Set URL as startup page" so that as soon as the tvbro icon is clicked, it goes directly to a webpage?

Before pestering you, I have tried entering eg microsoft.com with and without a query and it is not saved.

Again many thanks for the effort on this software.

**Comment by E-D-W-I-N** [comment]
@tvbrogreat First of all, thank you for your support and kind words.
Custom search engine URL must contain either https or http (depending on the protocol of the site you want to set as a search engine).

Just try https://www.microsoft.com/ for example.

If you have any other questions, I'll be glad to help you at any time 👌

**Comment by tvbrogreat** [comment]
Thanks for the fast reply!

I just saw that the problem is that the device, nvidia shield 2015 with android tv 9, does not save the custom search engine setting and the url.

I set Choose default search engine: custom, input the url for example https://github.com/ or https://search.aol.com/aol/search?q=[query]

After that, to close the MAIN options window I either press OK on the remote for all the other options or click with a usb mouse at SHORTCUTS and then elsewhere in the screen.

When I click again on the gears icon, the Choose default search engine: custom is there but the focus is at the URL field below which is empty with the cursor blinking on the start of the "Search engine URL with query placeholder [query]" line waiting for input.

Perhaps a Save button after the last option on the MAIN tab would force the device to save all the options correctly.

**Comment by E-D-W-I-N** [comment]
@tvbrogreat Yeah, I see what you talking about. I don't know about the save button, by the end of a day I'm not a maintainer/author of this project, so, this is up to him to accept any changes like so.

But the part about URL field being empty after choosing a custom search engine is definitely some kind of bug.
Please consider making an issue about it [here](https://github.com/truefedex/tv-bro/issues) because pull request's comments isn't a very good place for bugs discussions.

**Pull request merged**
