### PR TITLE
Intent url fix

### PR DESCRIPTION
**Pull request by elpaxel**
Fix opening intent:// url from javascript and by left click.

### CODE REVIEW

**Comment by truefedex** [comment]
@elpaxel please explain why this is needed. Can you tell me where the intent:// URLs is used? And why open them through onOpenInExternalAppRequested if askUserAndOpenInExternalApp is used further in the code? Your code will automatically open the external application, but other TVbro users have complained about this behavior, so a permission request from the user has been added.

**Comment by elpaxel** [comment]
So right now if I'm doing this on the page:

`location.href = "intent://some_video_url.m3u8#Intent;action=android.intent.VIEW;scheme=https;type=video/*;S.subtitles_location=/some_subtitles.vtt;end";`

then TVbro says there is no app for this type of url.

I have used "onOpenInExternalAppRequested" because there is "Intent.parseUri(url, Intent.URI_INTENT_SCHEME)". I guess this way my url parsed correctly and "subtitles_location" that I use for VLC will be in place. Second reason because that function is the old version of intent handling I guess ([old fix](https://github.com/truefedex/tv-bro/pull/4)).

As for the code further in and "askUserAndOpenInExternalApp", it uses "Intent(Intent.ACTION_VIEW, uri)". I guess it creates new Intent with ACTION_VIEW and expects "plain" url. Something like "intent://some_video_url.m3u8". But this way (again I guess) "subtitles_location" will be stripped. I have made this assumptions by reading code because as of now it is failing [there](https://github.com/truefedex/tv-bro/blob/5927391b7630dff9a2c2b31530365fde0a2ee7d7/app/src/main/java/com/phlox/tvwebbrowser/activity/main/MainActivity.kt#L1157).

It is working fine with my fix but my reflections may be wrong because I don't use Kotlin and didn't read your code too deeply.

**Comment by elpaxel** [comment]
So I have changed this:
`val intent = Intent(Intent.ACTION_VIEW, uri)`
to this:
`val intent = Intent.parseUri(url, Intent.URI_INTENT_SCHEME)`
and everything working fine.

Urls checked and working fine:
`intent://some_video_url.m3u8#Intent;action=android.intent.VIEW;scheme=https;type=video/*;S.subtitles_location=/some_subtitles.vtt;end`
`https://some_video_url.m3u8`

**Comment by truefedex** [comment]
@elpaxel Thank you for explanations. I think may be I will change a bit this behaviour later.

**Pull request merged**
